### ISSUE TITLE
How to determine the offset of handleMouseClickFunc

### ISSUE THREAD

**Issue by darabi** [fpw/BlackMagic#1]
Hi Folke,

I think I understand the principle which you kindly describe [in this forum post](https://forums.x-plane.org/index.php?/forums/topic/153812-blackmagic-vr-support-for-sasl-panels) and would like to extend the plugin for the SASL version which comes with one of my planes.

Would you explain how I can get the offset of the function (`0x890F0` in the code below) in a certain version of the SASL plugin?

```
if (id == 0x8A520) { // SASL 2.5.1 20171214 Commercial Edition
   saslWindow.handleMouseClickFunc = XPLMHandleMouseClick_f((void *) sasl + 0x890F0);
```

Thank you

Kami

**Comment by fpw** [comment]
Hi Kami,

you will need a disassembler like IDA Pro for this. 

The ID value is the relative address of the XPluginStart function inside the SASL plugin, I use the address to identify the plugin version because I didn't find other meta information to uniquely identify a SASL version.

The other offset is the address of SASL's internal click handler. To find that, I search for the place where SASL calls XPLMCreateWindowEx. Since SASL has only one window, there is only one call to XPLMCreateWindowEx. Looking at the assembly code for that, there are a few `lea` operations that load the offsets of the different event handlers. The first of these is the one we're searching.

Here's a screenshot for the example above:
<img width="192" alt="example" src="https://user-images.githubusercontent.com/5798899/47439929-870eac80-d7ad-11e8-962b-18a31b3bf77b.png">

Above the call to XPLMCreateWindowEx, the first `lea` loads 1800890F0. Since the code is position-independent, only the lower 3 bytes matter, i.e. 0x890F0 is the offset for Blackmagic.

If this is too difficult or you don't have access to a disassembler that can do that, feel free to attach a specific SASL xpl and I'll get the values for you so you can test them.

Grüße aus Lübeck
Folke

**Comment by darabi** [comment]
With your detailed instructions and IDA Free, it was very easy to find out the offset.

I made a short flight with Picus X Aquila 210 using the Oculus Rift and was absolutely impressed.

I will shortly send a PR for the SASL versions which I have.

Thank you for this great hack!

**Comment by fpw** [comment]
This plugin is now obsolete, the functionality has been integrated into MoveVR. The MoveVR implementation does not depend on the SASL version anymore and works for all versions.
